FROM golang:latest AS builder

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update; apt-get -y install ca-certificates

COPY . /go/src/github.com/fioprotocol/fio.etl
WORKDIR /go/src/github.com/fioprotocol/fio.etl

RUN go build -ldflags "-s -w" -o /consumer cmd/fioetl/main.go


FROM debian:10 AS ssl
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade && apt-get install -y ca-certificates && \
    addgroup --gid 8000 --system fio && adduser -uid 8000 --ingroup fio --system --home /home/fio fio


### try to build a lighter container
FROM scratch
COPY --from=builder /consumer /consumer

# this gets libssl1.1, openssl, and libc6 which we need for TLS, not tiny, but saves about 1 GiB in final image size
COPY --from=ssl /etc/ca-certificates /etc/ca-certificates
COPY --from=ssl /etc/ssl /etc/ssl
COPY --from=ssl /usr/share/ca-certificates /usr/share/ca-certificates
COPY --from=ssl /usr/lib /usr/lib
COPY --from=ssl /lib /lib
COPY --from=ssl /lib64 /lib64

# Need passwd and group for user id mapping,
# and the home dir, can't use 'RUN mkdir ...' in a 'FROM scratch', so copy.
COPY --from=ssl /etc/passwd /etc/passwd
COPY --from=ssl /etc/group /etc/group
COPY --from=ssl --chown=fio:fio /home/fio /home/fio

USER fio
WORKDIR /home/fio

CMD ["/consumer"]

